### PR TITLE
add localization, English and Korean, update show text to use this

### PR DESCRIPTION
**Pull request by ncossor**
Hi all, can someone review this (you will have to trust YoungHoon on the korean string values, unless you speak Korean)

### CODE REVIEW

**Review by pouriaalmassi — DISMISSED** [review]
Looks good to me. I wonder if we might find a place to store all of the LocalizedStringKey properties like the ones in ContentView.

**Comment by ncossor** [comment]
re storing all of the LocalizedStringKey properties being 'centralized'.. swings and roundabouts. They must all be centralized in the <language-specific>Localizable.strings files anyway, but if we wanted to put them into (say) a single Swift file.. then 
1. we would need pretty formalized naming conventions, as the scope would be app wide
2. the source file referencing the lookup key is disjoint with that common file

Given we only have a skeleton project at present, I suggest we come back and refactor along those lines once we have a more concrete app design and implementation, if we think it worthwhile.

**Comment by ncossor** [comment]
Hi @jimmyhoran 
I don't have access to merge("Merging is blocked"). Can you do this pls ?
Thx

**Review by jimmyhoran — DISMISSED** [review]
Nice one 👍
Maybe @hayounghoon can give it a review.

**Comment by ncossor** [comment]
thanks

**Review by jimmyhoran — APPROVED** [review]

**Comment by hayounghoon** [comment]
> Nice one 👍
> Maybe @hayounghoon can give it a review.

Yeah, we checked it together.
Perfect!

**Review by hayounghoon — COMMENTED** [review]
Good!
Extend this program without thinking of the Korean version, I will check it in this occasionally!

**Pull request merged**
